In [13]:
import pandas as pd 

df1 =pd.DataFrame({
    "FellowshipId":[1001,1002,1003,1004],
    'FirstName':["Frodo","Samwise","Gandalf","Pippin"],
    'Skills':['Hiding','Garendening','Spells','Fireworks']
})

df2=pd.DataFrame({
     "FellowshipId":[1001,1002,1006,1007,1008],
     'FirstName':["Frodo","Samwise","Legolas","Elrond","Barromir"],
     'Age':[50,39,2931,6520,51]
})
display(df1)
display(df2)

   FellowshipId FirstName       Skills
0          1001     Frodo       Hiding
1          1002   Samwise  Garendening
2          1003   Gandalf       Spells
3          1004    Pippin    Fireworks

   FellowshipId FirstName   Age
0          1001     Frodo    50
1          1002   Samwise    39
2          1006   Legolas  2931
3          1007    Elrond  6520
4          1008  Barromir    51

In [14]:
# inner join

mergedDf=df1.merge(df2)
mergedDf
mergedDf=df1.merge(df2,on=['FellowshipId','FirstName'],how='inner')
mergedDf

   FellowshipId FirstName       Skills  Age
0          1001     Frodo       Hiding   50
1          1002   Samwise  Garendening   39

In [17]:
# outer join

mergedDf=df1.merge(df2,how='outer')
mergedDf

   FellowshipId FirstName       Skills     Age
0          1001     Frodo       Hiding    50.0
1          1002   Samwise  Garendening    39.0
2          1003   Gandalf       Spells     NaN
3          1004    Pippin    Fireworks     NaN
4          1006   Legolas          NaN  2931.0
5          1007    Elrond          NaN  6520.0
6          1008  Barromir          NaN    51.0

In [19]:
# left join

mergedDf=df1.merge(df2,how='left')
mergedDf

   FellowshipId FirstName       Skills   Age
0          1001     Frodo       Hiding  50.0
1          1002   Samwise  Garendening  39.0
2          1003   Gandalf       Spells   NaN
3          1004    Pippin    Fireworks   NaN

In [20]:
# right join

mergedDf=df1.merge(df2,how='right')
mergedDf

   FellowshipId FirstName       Skills   Age
0          1001     Frodo       Hiding    50
1          1002   Samwise  Garendening    39
2          1006   Legolas          NaN  2931
3          1007    Elrond          NaN  6520
4          1008  Barromir          NaN    51